version: "3"

services:
  db:
    image: postgres
    volumes:
      - pgsql-dqs-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
  dqs-bot:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile

volumes:
  pgsql-dqs-data:
